# Generated by Django 5.0.6 on 2024-05-28 10:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('submitted_date', models.DateField(default=django.utils.timezone.now)),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
                ('t_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.teacher')),
            ],
        ),
    ]
