# Generated by Django 5.0.6 on 2024-05-29 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replyto', to='app1.complaints')),
                ('t_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replyby', to='app1.complaints')),
            ],
        ),
    ]
