# Generated by Django 5.1 on 2024-08-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantshop',
            name='gender',
        ),
    ]
